# Basics of Numpy

In [6]:
#importing 
import numpy as np

#creating array 
a=np.array([1,2,3,4,5])
print(a)
#type of data 
print(type(a))
#accessing first 
a[0]

[1 2 3 4 5]
<class 'numpy.ndarray'>


1

In [3]:
print(a.shape) #dimensions of array - 5 columns , 0 rows - 3  dimesnional array is possible as well 

(5,)


In [5]:
b=np.array([[1], [2], [3], [4], [5]]) #2d matrix 
print(b)
print(b.shape) #type of shape 
b[0][0]

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


1

In [7]:
c= np.array([[1,2,3], [4,5,6]])
print(c)
print(c.shape) #type of shape 
print(c[1][1]) #1st row, 1st col element 

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [14]:
a=np.zeros((3,3)) #creating a 3*3 matrix of zeros 
print(a)
print(type(a))
b=np.ones((2,3)) #creating a 2*3 matrix of ones 
print(b)

#array of some constant 
c=np.full((3,2), 5) #filling the matrix with all elements as 5 
print(c)

#identity matrix - size/square matrix 
d=np.eye(4) #for identity matrix 
print(d)

#random matrix - generates random matrix 
randommat=np.random.random((2,3)) 
print(randommat)



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.86076555 0.48572729 0.80418751]
 [0.95577874 0.78149504 0.68519059]]


In [18]:
#reading elements of rand matrix 
print(randommat[ :,0 ]) #prints first column 

[0.86076555 0.95577874]


In [19]:
#updating an element 
randommat[1,1:]=1 #1st row , last 2 columns
print(randommat)

[[0.86076555 0.48572729 0.80418751]
 [0.95577874 1.         1.        ]]


In [34]:
#setting rows and columns 

z= np.zeros((3,3), dtype=np.int64) #changing data type from float to int 
print(z)
z[1,:]=5
z[2,2:3]=2
z[:,-1]=7
print(z)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [35]:
#data types 

print(z.dtype)

int64


# Mathematical Operations

In [40]:
#math operations 
x= np.array([[1,2],[3,4]])
y=np.array([[5,6] ,[7,8]])
print(x)
print(" ")
print(y)
print(" ")
print(x+y)
print(" ")
print(np.add(x,y))
print(" ")
print(np.subtract(x,y))
#both add operations give same result 

[[1 2]
 [3 4]]
 
[[5 6]
 [7 8]]
 
[[ 6  8]
 [10 12]]
 
[[ 6  8]
 [10 12]]
 
[[-4 -4]
 [-4 -4]]


In [42]:
#multiplaction and division 
print(x*y)
print(" ")
print(np.multiply(x,y))
print(" ")
print(x/y)
print(" ")
print(np.divide(x,y))

#this is element wise multiplcation and divison, not dot product 

[[ 5 12]
 [21 32]]
 
[[ 5 12]
 [21 32]]
 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
print(np.sqrt(x)) #square root 

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [46]:
#matrix multiplication and dot products 
print(x,y)
print(" ")
print(y)
print(" ")
print(x.dot(y))  #dot product 
print(" ")
#or 
print(np.dot(x,y)) #dot product 2nd method 

[[1 2]
 [3 4]] [[5 6]
 [7 8]]
 
[[5 6]
 [7 8]]
 
[[19 22]
 [43 50]]
 
[[19 22]
 [43 50]]


In [49]:
#multiplication of vector - linear array 
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(a.dot(b))

#[1 2 3 4] [1]                 #this is vector muliplication 
 #         [2]
  #        [3]
   #       [4] 
 

30


In [54]:
#sum of elements 
print(a)
print(sum(a))
#or
print(np.sum(a))
 


[1 2 3 4]
10
10
10


In [60]:
print(x)
print(" ")
print(np.sum(x,axis=0))
#axis is optional parameter, takes sum to be sum of elem along 
#the columns 
#1+3=4
#4+2=6

print(" ")

print(np.sum(x,axis=1)) 
#axis is optional parameter, takes sum to be sum of elem along 
#the rows 
#1+2=3
#4+3=7



[[1 2]
 [3 4]]
 
[4 6]
 
[3 7]


# Stacking

In [70]:
#stacking of arrays

aa=np.array([1,2,3,4])
bb=np.array([1,2,3,4])
print(aa)
#print(bb)

print(" ")

bb=bb*2
print(bb)

[1 2 3 4]
[1 2 3 4]
 
[2 4 6 8]


# Concatenation

In [79]:
#concatenating arrays 
np.stack((aa,bb),axis=1) #along rows 

print(" ")

a=np.stack((aa,bb), axis=0) #along columns 
print(a)

 
[[1 2 3 4]
 [2 4 6 8]]


# Shaping and Reshaping 

In [88]:
#Reshape a numpy array 

#print(a)
#changing shape to 4 rows 2 columns 

a=a.reshape((4,2))
print(a)

#now it has 4 rows and 2 columns, shape has been changed i.e. 
#dimensions are changed now 

print(" ")

cc=a.reshape((8,1))
print(cc)

print(" ")

dd= a.reshape((8,)) #gives linear array 
print(dd)

#if you do not want to calculate the number of columns
#here number of cols are automatically generated

print(" ")
ee= a.reshape((4,-1))
#or 
#ee= a.reshape((-1,4)) #if you dont know number of rows 
#automatically calculated then 
print(ee)

[[1 2]
 [3 4]
 [2 4]
 [6 8]]
 
[[1]
 [2]
 [3]
 [4]
 [2]
 [4]
 [6]
 [8]]
 
[1 2 3 4 2 4 6 8]
 
[[1 2]
 [3 4]
 [2 4]
 [6 8]]


# Numpy Random Module

rand: random values in a given shape 
randn: return a sample from the 'standard normal ' distribution 
randint: return random integers from low(inclusive) to high (exclusive)
random: return random floats in the half open interval- [0.0,1.0)

choice: generates a random shuffle from a given 1-D array 

shuffle: shuffles the contents of a sequence 

In [91]:
a= np.arange(10) #arranges numbers from 1 to 10 in an array 
print(a)



[0 1 2 3 4 5 6 7 8 9]


In [98]:
import random
#import np.randome as n

np.random.seed(1) # done in order to ensure you get the same 
#set of randome values every time , pesuodrandom
np.random.shuffle(a) #shuffling elements of array
print(a)



[5 2 8 0 3 6 4 1 9 7]


In [104]:
#returns values from a standard normal distribution 
a=np.random.randn(2,3)
print(a) #random values in a 2*3 array, 2 rows and 3 columns 


[[ 0.15633654  0.95765256 -0.47452742]
 [-0.53082286 -0.2556854   1.00990117]]


In [100]:
a=np.random.randint(5,10,2) #gives 2 random ints in the range 5-10
print(a)

[5 7]


In [103]:
#Randomly pick one element from array 
elem= np.random.choice([1,2,3,4])
print(elem)

3


# Stats

(i) min, max
(ii) mean 
(iii) median 
(iv) average 
(v) VARIANCE 
(vi) standard deviation 


In [109]:
a=np.array([[1,2,3,4],[7,6,2,0]])
print(a)

#specifiy axis for direction in case of 2d array 

print(np.min(a)) #finds min in whole 2d array 
print(np.min(a,axis=0)) #finds min in column comparison 
print(np.min(a,axis=1)) #finds min in row comparsion 

[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [118]:
#mean 
b= np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))

#specify axis properly 
print(np.mean(a, axis=0))
print(np.mean(a, axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [119]:
c=np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [122]:
#Mean v.s. Average (weighted average)

print(np.mean(c))

#weights specifiying 
wts=np.array([1,1,1,1,1])
print(np.average(c, weights=wts))

2.4
2.4


In [124]:
#standard deviation 

#by formula 
#sigma= Math.sqrt(1/n * summation of (xi-mu)**2)

u=np.mean(c)
mystd= np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

#inbuilt 
print(np.std(c))



1.854723699099141
1.854723699099141


In [128]:
#variance 

#by formula 
print(mystd**2)

#by inbuilt np 
print(np.var(c))

3.440000000000001
3.4400000000000004
